#!/usr/bin/env python3
"""Generate the Code-view architecture diagram from the real import graph.

The Code page of ``docs/architecture/code_architecture.mdg`` is a *lockfile*:
every significant module in ``mdg_drawio/`` becomes a ``uml.Class`` node, and
every internal import between modules becomes a ``uml.Dependency`` edge. The
file is fully derived from the source tree, so it can never silently drift.

Workflow::

    python scripts/generate_code_arch.py            # print to stdout
    python scripts/generate_code_arch.py --write     # rewrite the .mdg
    python scripts/generate_code_arch.py --check      # exit 1 if stale

``tests/test_code_architecture_graph.py`` runs ``--check`` semantics so a
forgotten regeneration fails CI.

Structure — the code view mirrors the C4 hierarchy so it reads top-down:

    uml.Package(<container>)        # C4 Container (mdg_drawio subpackage)
        uml.Package(<component>)    # C4 Component (from the realized-by traces)
            uml.Class(<module>)     # the source module(s) that realize it

Modelling rules (kept deliberately simple and architecture-aligned):

* A "significant module" is any ``*.py`` under ``mdg_drawio/`` except
  ``__init__.py`` / ``__main__.py``.
* Which Component a module belongs to comes from the ``realized-by`` traces in
  ``c4_architecture.mdg`` — the model, not this script, owns that mapping.
* A cross-package ``from mdg_drawio.<pkg> import ...`` resolves to the container
  package node ``<pkg>`` (the public API surface).
* A relative import resolves to the specific module node it targets.
* A top-level module (e.g. ``cli.py``) has no container dir, so its Component
  package sits at the top level.
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG_DIR = ROOT / "mdg_drawio"
MDG_PATH = ROOT / "docs" / "architecture" / "code_architecture.mdg"
C4_MDG = ROOT / "docs" / "architecture" / "c4_architecture.mdg"

_TRACE_RE = re.compile(r"^trace\s+(\w+)\s*->\s*code\.(\w+)\s*:\s*realized-by\s*$")
_CONTAINER_RE = re.compile(r'c4\.Container\((\w+),\s*"([^"]*)"')
_COMPONENT_RE = re.compile(r'c4\.Component\((\w+),\s*"([^"]*)"')

_HEADER = (
    '---\n'
    'title: "Code Architecture for mdg-drawio"\n'
    'page: "Code"\n'
    'mode: layered\n'
    'direction: TB\n'
    '---\n\n'
    'uml.UML("[Code] mdg-drawio — Container ▸ Component ▸ module '
    '(generated by scripts/generate_code_arch.py — do not edit by hand)")\n'
)


def _significant_modules() -> list[Path]:
    """All source modules under mdg_drawio/, excluding package/entry files."""
    return sorted(
        p
        for p in PKG_DIR.rglob("*.py")
        if "__pycache__" not in p.parts
        and p.name not in ("__init__.py", "__main__.py")
    )


def _rel(path: Path) -> str:
    return str(path.relative_to(PKG_DIR))


def _node_id(rel: str) -> str:
    """Node id for a module rel path, e.g. ``layout/_types.py`` -> ``layout__types``."""
    return rel.removesuffix(".py").replace("/", "_")


def _package_id(pkg_rel: str) -> str:
    """Node id for a package dir, e.g. ``notation/_core`` -> ``notation__core``."""
    return pkg_rel.replace("/", "_")


def _dotted_index() -> dict[str, str]:
    """Map every importable dotted path to a target node id.

    Modules map to their module node; packages (``__init__.py``) map to their
    package node.
    """
    index: dict[str, str] = {}
    for path in PKG_DIR.rglob("*.py"):
        if "__pycache__" in path.parts:
            continue
        rel = path.relative_to(PKG_DIR)
        if rel.name == "__init__.py":
            pkg_rel = str(rel.parent)
            dotted = ".".join(("mdg_drawio", *rel.parent.parts))
            index[dotted] = _package_id(pkg_rel)
        else:
            dotted = ".".join(("mdg_drawio", *rel.with_suffix("").parts))
            index[dotted] = _node_id(str(rel))
    return index


def _resolve_import(node: ast.ImportFrom, source: Path) -> str | None:
    """Resolve an ``ImportFrom`` on *source* to its dotted mdg_drawio target."""
    if node.level:
        base_parts = ("mdg_drawio", *source.relative_to(PKG_DIR).with_suffix("").parts)
        base = base_parts[: len(base_parts) - node.level]
        return ".".join((*base, node.module)) if node.module else ".".join(base)
    if node.module and node.module.startswith("mdg_drawio"):
        return node.module
    return None


def _import_targets(node: ast.AST, source: Path) -> list[str]:
    """Dotted mdg_drawio target(s) of any import node on *source*.

    Handles both ``from mdg_drawio.x import ...`` (``ast.ImportFrom``) and plain
    ``import mdg_drawio.x`` / ``import mdg_drawio.x as y`` (``ast.Import``). The
    ``as`` alias never changes the imported module path, so it is normalized
    away. Both forms are real dependencies and must appear in the Code view.
    """
    if isinstance(node, ast.ImportFrom):
        dotted = _resolve_import(node, source)
        return [dotted] if dotted is not None else []
    if isinstance(node, ast.Import):
        return [
            alias.name
            for alias in node.names
            if alias.name == "mdg_drawio" or alias.name.startswith("mdg_drawio.")
        ]
    return []


def import_edges() -> list[tuple[str, str]]:
    """Return sorted (src_id, tgt_id) for every internal module import."""
    index = _dotted_index()
    edges: set[tuple[str, str]] = set()
    for module in _significant_modules():
        src_id = _node_id(_rel(module))
        tree = ast.parse(module.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            for dotted in _import_targets(node, module):
                tgt_id = index.get(dotted)
                if tgt_id is not None and tgt_id != src_id:
                    edges.add((src_id, tgt_id))
    return sorted(edges)


# ── C4 model inputs (Component/Container names + realized-by traces) ──────────


def _c4_labels(pattern: re.Pattern[str]) -> dict[str, str]:
    text = C4_MDG.read_text(encoding="utf-8")
    return dict(pattern.findall(text))


def _component_modules() -> dict[str, set[str]]:
    """``{component_id: {module_node_id}}`` from the realized-by traces."""
    mapping: dict[str, set[str]] = {}
    for line in C4_MDG.read_text(encoding="utf-8").splitlines():
        match = _TRACE_RE.match(line.strip())
        if match:
            mapping.setdefault(match.group(1), set()).add(match.group(2))
    return mapping


def _container_of(node_id: str, node_to_rel: dict[str, str]) -> str | None:
    """The container (top-level package dir) a module belongs to, or None."""
    rel = node_to_rel[node_id]
    return rel.split("/", 1)[0] if "/" in rel else None


# ── Node tree rendering (Container ▸ Component ▸ module) ──────────────────────


def _render_nodes() -> str:
    node_to_rel = {_node_id(_rel(p)): _rel(p) for p in _significant_modules()}
    component_modules = _component_modules()
    container_label = _c4_labels(_CONTAINER_RE)
    component_label = _c4_labels(_COMPONENT_RE)

    # component -> container (all of a component's modules share one container)
    comp_container: dict[str, str | None] = {}
    by_container: dict[str | None, list[str]] = {}
    for comp, nodes in component_modules.items():
        containers = {_container_of(n, node_to_rel) for n in nodes}
        assert len(containers) == 1, f"{comp} spans containers {containers}"
        container = containers.pop()
        comp_container[comp] = container
        by_container.setdefault(container, []).append(comp)

    def render_component(comp: str, depth: int) -> list[str]:
        pad = "    " * depth
        out = [f'{pad}uml.Package({comp}, "{component_label.get(comp, comp)}"):']
        for node in sorted(component_modules[comp]):
            name = node_to_rel[node].rsplit("/", 1)[-1].removesuffix(".py")
            out.append(f'{pad}    uml.Class({node}, "{name}")')
        return out

    lines: list[str] = []
    for container in sorted(c for c in by_container if c is not None):
        label = container_label.get(container, container)
        lines.append(f'uml.Package({container}, "{label}"):')
        for comp in sorted(by_container[container]):
            lines.extend(render_component(comp, depth=1))
    for comp in sorted(by_container.get(None, [])):
        lines.extend(render_component(comp, depth=0))

    return "\n".join(lines)


def render() -> str:
    """Return the full deterministic content of the Code-view .mdg file."""
    nodes = _render_nodes()
    edges = "\n".join(
        f"uml.Dependency({src}, {tgt})" for src, tgt in import_edges()
    )
    return f"{_HEADER}\n{nodes}\n\n{edges}\n"


def main() -> int:
    content = render()
    if "--write" in sys.argv:
        MDG_PATH.write_text(content, encoding="utf-8")
        print(f"Wrote {MDG_PATH} ({len(import_edges())} import edges)")
        return 0
    if "--check" in sys.argv:
        current = MDG_PATH.read_text(encoding="utf-8") if MDG_PATH.exists() else ""
        if current != content:
            print(
                "code_architecture.mdg is stale. "
                "Run: python scripts/generate_code_arch.py --write"
            )
            return 1
        print("code_architecture.mdg is in sync with the import graph.")
        return 0
    print(content, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
