#!/usr/bin/env python3
"""Generate the human-readable traceability matrix.

Emits ``docs/architecture/traceability.md`` — a flat, greppable Container ▸
Component ▸ module table derived from the `realized-by` traces in
``c4_architecture.mdg``. Complements the diagrams with a queryable artifact.

    python scripts/generate_traceability_matrix.py            # print
    python scripts/generate_traceability_matrix.py --write     # rewrite the .md
    python scripts/generate_traceability_matrix.py --check      # exit 1 if stale

The matrix is a lockfile: `check_model` runs `--check` so it can never drift.
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path
from types import ModuleType

ROOT = Path(__file__).resolve().parent.parent
ARCH_DIR = ROOT / "docs" / "architecture"
C4_MDG = ARCH_DIR / "c4_architecture.mdg"
DECISIONS_MDG = ARCH_DIR / "decisions.mdg"
OUT = ARCH_DIR / "traceability.md"

_TRACE_RE = re.compile(r"^trace\s+(\w+)\s*->\s*code\.(\w+)\s*:\s*realized-by\s*$")
_SATISFIES_RE = re.compile(
    r"^trace\s+(\w+)\s*->\s*decisions\.(\w+)\s*:\s*satisfies\s*$"
)
_CONTAINER_RE = re.compile(r'c4\.Container\((\w+),\s*"([^"]*)"')
_COMPONENT_RE = re.compile(r'c4\.Component\((\w+),\s*"([^"]*)"')
_CLASS_RE = re.compile(r'uml\.Class\((\w+),\s*"([^"]*)"')

_HEADER = (
    "# Traceability matrix\n\n"
    "Generated by `scripts/generate_traceability_matrix.py` — do not edit by "
    "hand.\n\n"
    "Each C4 Component and the module(s) that realize it (from the "
    "`realized-by` traces in `c4_architecture.mdg`).\n"
    "Verification traceability is coverage-derived via `make verification`.\n\n"
)


def _load_code_generator() -> ModuleType:
    path = ROOT / "scripts" / "generate_code_arch.py"
    spec = importlib.util.spec_from_file_location("generate_code_arch", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules.setdefault("generate_code_arch", module)
    spec.loader.exec_module(module)
    return module


def _labels(pattern: re.Pattern[str]) -> dict[str, str]:
    return dict(pattern.findall(C4_MDG.read_text(encoding="utf-8")))


def render() -> str:
    gen = _load_code_generator()
    node_to_rel = {gen._node_id(gen._rel(p)): gen._rel(p)
                   for p in gen._significant_modules()}
    component_label = _labels(_COMPONENT_RE)
    container_label = _labels(_CONTAINER_RE)

    rows: list[tuple[str, str, str]] = []
    for line in C4_MDG.read_text(encoding="utf-8").splitlines():
        match = _TRACE_RE.match(line.strip())
        if not match:
            continue
        comp, node = match.group(1), match.group(2)
        rel = node_to_rel[node]
        container = rel.split("/", 1)[0] if "/" in rel else rel.removesuffix(".py")
        rows.append((container, comp, rel))

    # collapse multiple modules per component onto one row
    by_component: dict[str, tuple[str, list[str]]] = {}
    for container, comp, rel in rows:
        by_component.setdefault(comp, (container, []))[1].append(rel)

    lines = [_HEADER, "| Container | Component | Realized by |", "|---|---|---|"]
    ordered = sorted(
        by_component.items(),
        key=lambda kv: (
            container_label.get(kv[1][0], kv[1][0]),
            component_label.get(kv[0], kv[0]),
        ),
    )
    for comp, (container, rels) in ordered:
        c_label = container_label.get(container, container)
        comp_label = component_label.get(comp, comp)
        modules = "<br>".join(f"`{r}`" for r in sorted(rels))
        lines.append(f"| {c_label} | {comp_label} | {modules} |")

    lines.extend(_decisions_section(component_label))
    return "\n".join(lines) + "\n"


def _decisions_section(component_label: dict[str, str]) -> list[str]:
    """Table of architecture decisions and the Components that satisfy them."""
    adr_label = dict(_CLASS_RE.findall(DECISIONS_MDG.read_text(encoding="utf-8")))
    by_adr: dict[str, list[str]] = {}
    for line in C4_MDG.read_text(encoding="utf-8").splitlines():
        match = _SATISFIES_RE.match(line.strip())
        if match:
            by_adr.setdefault(match.group(2), []).append(match.group(1))

    lines = ["", "## Architecture decisions", ""]
    lines += ["| Decision | Satisfied by |", "|---|---|"]
    for adr in sorted(by_adr):
        satisfiers = ", ".join(
            component_label.get(c, c) for c in sorted(by_adr[adr])
        )
        lines.append(f"| {adr_label.get(adr, adr)} | {satisfiers} |")
    return lines


def main() -> int:
    content = render()
    if "--write" in sys.argv:
        OUT.write_text(content, encoding="utf-8")
        print(f"Wrote {OUT}")
        return 0
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != content:
            print(
                "traceability.md is stale. "
                "Run: python scripts/generate_traceability_matrix.py --write"
            )
            return 1
        print("traceability.md is in sync with the model.")
        return 0
    print(content, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
